[2025-10-01T12:15:59.091+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:15:59.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:15:59.140+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:15:59.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:16:12.584+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:16:12.887+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:16:12.885+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:16:13.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 14.941 seconds
[2025-10-01T12:16:43.766+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:16:43.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:16:44.026+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:16:43.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:17:00.561+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:17:00.792+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:17:00.789+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:17:00.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 17.209 seconds
[2025-10-01T12:17:31.372+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:17:31.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:17:31.392+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:17:31.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:17:35.068+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:17:35.603+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:17:35.601+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:17:35.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 4.528 seconds
[2025-10-01T12:18:06.807+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:06.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:18:06.818+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:18:06.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:08.414+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:08.498+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:18:08.497+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:18:08.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.829 seconds
[2025-10-01T12:18:39.699+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:39.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:18:39.726+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:18:39.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:41.080+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:18:41.191+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:18:41.189+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:18:41.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.901 seconds
[2025-10-01T12:19:12.768+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:12.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:19:12.778+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:12.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:14.366+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:14.570+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:14.563+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:19:14.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.163 seconds
[2025-10-01T12:19:42.706+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:42.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:19:42.716+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:42.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:44.083+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:44.163+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:44.162+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:19:44.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.627 seconds
[2025-10-01T12:19:47.929+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:47.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:19:47.945+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:47.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:49.802+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:19:49.885+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:19:49.883+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:19:50.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.142 seconds
[2025-10-01T12:20:00.269+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:00.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:20:00.281+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:00.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:01.735+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:01.797+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:01.796+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:20:01.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.685 seconds
[2025-10-01T12:20:05.522+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:05.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:20:05.537+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:05.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:07.002+0000] {processor.py:925} INFO - DAG(s) 'core_telemetry_pipeline' retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:07.187+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:07.185+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-10-01T12:20:07.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.977 seconds
[2025-10-01T12:20:09.805+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:09.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:20:09.833+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:09.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:10.023+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:09.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:20:10.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:10.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.540 seconds
[2025-10-01T12:20:40.893+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:40.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:20:40.906+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:40.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:40.960+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:20:40.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:20:40.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:20:41.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.176 seconds
[2025-10-01T12:21:11.215+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:11.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:21:11.229+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:21:11.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:11.291+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:21:11.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:21:11.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:11.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.175 seconds
[2025-10-01T12:21:42.145+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:42.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:21:42.160+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:21:42.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:42.217+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:21:42.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:21:42.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:21:42.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.177 seconds
[2025-10-01T12:22:12.631+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:12.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:22:12.642+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:22:12.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:12.726+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:22:12.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:22:12.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:12.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.204 seconds
[2025-10-01T12:22:43.414+0000] {processor.py:186} INFO - Started process (PID=252) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:43.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:22:43.421+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:22:43.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:43.475+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:22:43.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:22:43.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:22:43.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.167 seconds
[2025-10-01T12:23:14.188+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:14.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:23:14.199+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:23:14.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:14.269+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:23:14.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:23:14.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:14.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.203 seconds
[2025-10-01T12:23:44.792+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:44.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:23:44.802+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:23:44.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:44.862+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:23:44.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:23:44.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:23:44.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.164 seconds
[2025-10-01T12:24:15.291+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:15.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:24:15.299+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:24:15.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:15.347+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:24:15.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:24:15.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:15.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.137 seconds
[2025-10-01T12:24:45.731+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:45.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:24:45.738+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:24:45.737+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:45.781+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:24:45.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:24:45.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:24:45.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.174 seconds
[2025-10-01T12:25:16.203+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:16.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:25:16.213+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:25:16.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:16.270+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:25:16.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:25:16.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:16.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.224 seconds
[2025-10-01T12:25:46.769+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:46.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:25:46.776+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:25:46.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:46.863+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:25:46.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:25:46.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:25:46.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.183 seconds
[2025-10-01T12:26:17.533+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:17.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:26:17.540+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:26:17.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:17.586+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:26:17.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:26:17.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:17.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.158 seconds
[2025-10-01T12:26:48.428+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:48.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:26:48.439+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:26:48.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:48.503+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:26:48.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:26:48.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:26:48.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.168 seconds
[2025-10-01T12:27:19.458+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:19.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:27:19.503+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:27:19.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:19.586+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:27:19.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:27:19.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:19.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.637 seconds
[2025-10-01T12:27:50.659+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:50.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:27:50.679+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:27:50.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:50.856+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:27:50.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:27:50.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:27:50.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.324 seconds
[2025-10-01T12:28:21.607+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:21.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:28:21.618+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:28:21.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:21.681+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:28:21.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:28:21.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:21.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.190 seconds
[2025-10-01T12:28:52.532+0000] {processor.py:186} INFO - Started process (PID=363) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:52.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:28:52.545+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:28:52.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:52.391+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:28:52.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:28:52.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:28:52.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.194 seconds
[2025-10-01T12:29:22.792+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:22.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:29:22.810+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:29:22.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:22.896+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:29:22.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:29:22.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:22.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.220 seconds
[2025-10-01T12:29:54.046+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:54.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:29:54.055+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:29:54.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:54.111+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:29:54.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:29:54.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:29:54.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.190 seconds
[2025-10-01T12:30:24.560+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:24.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:30:24.570+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:30:24.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:24.615+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:30:24.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:30:24.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:24.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.170 seconds
[2025-10-01T12:30:54.923+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:54.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:30:54.933+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:30:54.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:55.033+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:30:55.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:30:55.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:30:55.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.197 seconds
[2025-10-01T12:31:25.586+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:25.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:31:25.595+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:31:25.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:25.648+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:31:25.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:31:25.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:25.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.142 seconds
[2025-10-01T12:31:55.916+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:55.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:31:55.924+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:31:55.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:55.974+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:31:55.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:31:55.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:31:56.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.145 seconds
[2025-10-01T12:32:26.754+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:26.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:32:26.762+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:32:26.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:26.820+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:32:26.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:32:26.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:26.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.153 seconds
[2025-10-01T12:32:57.149+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:57.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:32:57.158+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:32:57.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:57.219+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:32:57.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:32:57.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:32:57.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.174 seconds
[2025-10-01T12:33:27.675+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:27.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:33:27.683+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:33:27.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:27.735+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:33:27.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:33:27.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:27.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.139 seconds
[2025-10-01T12:33:58.491+0000] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:58.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:33:58.500+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:33:58.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:58.552+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:33:58.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:33:58.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:33:58.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.184 seconds
[2025-10-01T12:34:28.831+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:28.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:34:28.841+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:34:28.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:28.899+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:34:28.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:34:28.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:29.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.211 seconds
[2025-10-01T12:34:59.296+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:59.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:34:59.305+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:34:59.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:59.365+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:34:59.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:34:59.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:34:59.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.197 seconds
[2025-10-01T12:35:29.611+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:35:29.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:35:29.620+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:35:29.619+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:35:29.670+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:35:29.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:35:29.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:35:29.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.157 seconds
[2025-10-01T12:36:00.341+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:00.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:36:00.348+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:36:00.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:00.372+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:36:00.370+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:36:00.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:00.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.075 seconds
[2025-10-01T12:36:31.004+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:31.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:36:31.009+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:36:31.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:31.035+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:36:31.033+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:36:31.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:36:31.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.100 seconds
[2025-10-01T12:37:01.274+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:01.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:37:01.278+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:37:01.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:01.300+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:37:01.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:37:01.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:01.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.075 seconds
[2025-10-01T12:37:31.779+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:31.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:37:31.783+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:37:31.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:31.810+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:37:31.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:37:31.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:37:31.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.075 seconds
[2025-10-01T12:38:02.323+0000] {processor.py:186} INFO - Started process (PID=534) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:02.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:38:02.329+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:38:02.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:02.360+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:38:02.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:38:02.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:02.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.091 seconds
[2025-10-01T12:38:32.677+0000] {processor.py:186} INFO - Started process (PID=544) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:32.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:38:32.683+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:38:32.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:32.705+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:38:32.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:38:32.707+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:38:32.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.083 seconds
[2025-10-01T12:39:03.099+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:03.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:39:03.103+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:39:03.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:03.126+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:39:03.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:39:03.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:03.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.071 seconds
[2025-10-01T12:39:33.451+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:33.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:39:33.456+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:39:33.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:33.482+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:39:33.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:39:33.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:39:33.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.090 seconds
[2025-10-01T12:40:04.230+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:04.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:40:04.234+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:40:04.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:04.268+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:40:04.265+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:40:04.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:04.307+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.089 seconds
[2025-10-01T12:40:34.911+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:34.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:40:34.917+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:40:34.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:34.948+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:40:34.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:40:34.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:40:35.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.139 seconds
[2025-10-01T12:41:05.166+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:05.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:41:05.174+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:41:05.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:05.208+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:41:05.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:41:05.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:05.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.117 seconds
[2025-10-01T12:41:35.604+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:35.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:41:35.609+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:41:35.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:35.643+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:41:35.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:41:35.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:41:35.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.087 seconds
[2025-10-01T12:42:06.194+0000] {processor.py:186} INFO - Started process (PID=614) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:06.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:42:06.198+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:42:06.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:06.220+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:42:06.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:42:06.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:06.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.067 seconds
[2025-10-01T12:42:36.576+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:36.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:42:36.583+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:42:36.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:36.607+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:42:36.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:42:36.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:42:36.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.079 seconds
[2025-10-01T12:43:06.779+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:06.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:43:06.784+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:43:06.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:06.812+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:43:06.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:43:06.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:06.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.080 seconds
[2025-10-01T12:43:37.214+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:37.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:43:37.258+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:43:37.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:37.381+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:43:37.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:43:37.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:43:37.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.481 seconds
[2025-10-01T12:44:07.978+0000] {processor.py:186} INFO - Started process (PID=654) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:07.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:44:07.982+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:44:07.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:08.005+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:44:08.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:44:08.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:08.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.073 seconds
[2025-10-01T12:44:38.124+0000] {processor.py:186} INFO - Started process (PID=664) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:38.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:44:38.129+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:44:38.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:38.153+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:44:38.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:44:38.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:44:38.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.071 seconds
[2025-10-01T12:45:08.436+0000] {processor.py:186} INFO - Started process (PID=674) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:45:08.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T12:45:08.441+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:45:08.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:45:08.465+0000] {logging_mixin.py:190} INFO - [2025-10-01T12:45:08.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T12:45:08.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T12:45:08.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.084 seconds
[2025-10-01T18:46:18.134+0000] {processor.py:186} INFO - Started process (PID=676) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T18:46:18.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-01T18:46:18.160+0000] {logging_mixin.py:190} INFO - [2025-10-01T18:46:18.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T18:46:18.422+0000] {logging_mixin.py:190} INFO - [2025-10-01T18:46:18.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 46
    execution_date=,
    ^^^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-10-01T18:46:18.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-01T18:46:19.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.006 seconds
