[2025-10-04T07:39:01.428+0000] {processor.py:186} INFO - Started process (PID=42259) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:01.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T07:39:01.447+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:39:01.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:05.721+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:39:05.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 5, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T07:39:05.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:05.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 4.393 seconds
[2025-10-04T07:39:36.346+0000] {processor.py:186} INFO - Started process (PID=42288) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:36.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T07:39:36.354+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:39:36.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:38.074+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:39:38.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 5, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T07:39:38.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:39:38.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.793 seconds
[2025-10-04T07:40:08.978+0000] {processor.py:186} INFO - Started process (PID=42322) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:08.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T07:40:09.000+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:40:08.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:10.318+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:40:10.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 5, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T07:40:10.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:10.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.409 seconds
[2025-10-04T07:40:41.151+0000] {processor.py:186} INFO - Started process (PID=42349) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:41.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T07:40:41.163+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:40:41.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:42.319+0000] {logging_mixin.py:190} INFO - [2025-10-04T07:40:42.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 5, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T07:40:42.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T07:40:42.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.216 seconds
[2025-10-04T23:22:00.390+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:00.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:22:00.424+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:22:00.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:06.747+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:22:06.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:22:06.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:06.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 6.558 seconds
[2025-10-04T23:22:38.199+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:38.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:22:38.232+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:22:38.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:41.960+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:22:41.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:22:41.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:22:42.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 4.028 seconds
[2025-10-04T23:23:12.447+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:12.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:23:12.467+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:23:12.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:13.882+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:23:13.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:23:13.888+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:13.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.537 seconds
[2025-10-04T23:23:44.809+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:44.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:23:44.844+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:23:44.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:46.730+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:23:46.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:23:46.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:23:46.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.376 seconds
[2025-10-04T23:24:17.261+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:17.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:24:17.267+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:24:17.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:18.296+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:24:18.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:24:18.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:18.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.339 seconds
[2025-10-04T23:24:48.787+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:48.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:24:48.794+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:24:48.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:49.846+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:24:49.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:24:49.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:24:49.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.149 seconds
[2025-10-04T23:25:20.222+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:20.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:25:20.230+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:25:20.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:21.341+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:25:21.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:25:21.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:21.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.240 seconds
[2025-10-04T23:25:52.179+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:52.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:25:52.184+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:25:52.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:53.078+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:25:53.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:25:53.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:25:53.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.989 seconds
[2025-10-04T23:26:23.383+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:26:23.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:26:23.390+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:26:23.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:26:24.391+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:26:24.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:26:24.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:26:24.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.069 seconds
[2025-10-04T23:43:45.190+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:43:45.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:43:45.229+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:43:45.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:43:58.895+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:43:58.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:43:58.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:43:59.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 14.645 seconds
[2025-10-04T23:44:30.557+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:44:30.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:44:30.587+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:44:30.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:44:32.997+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:44:32.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:44:33.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:44:33.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.568 seconds
[2025-10-04T23:45:03.670+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:03.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:45:03.681+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:45:03.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:05.444+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:45:05.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:45:05.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:05.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.304 seconds
[2025-10-04T23:45:36.647+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:36.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:45:36.655+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:45:36.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:37.795+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:45:37.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:45:37.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:45:37.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.357 seconds
[2025-10-04T23:46:08.221+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:08.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:46:08.227+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:46:08.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:09.114+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:46:09.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:46:09.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:09.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.193 seconds
[2025-10-04T23:46:40.227+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:40.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:46:40.234+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:46:40.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:42.077+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:46:41.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:46:42.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:46:42.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.221 seconds
[2025-10-04T23:47:12.795+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:12.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:47:12.804+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:47:12.802+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:14.067+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:47:14.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:47:14.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:14.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.360 seconds
[2025-10-04T23:47:44.264+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:44.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:47:44.273+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:47:44.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:45.363+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:47:45.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:47:45.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:47:45.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.184 seconds
[2025-10-04T23:48:15.568+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:15.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:48:15.575+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:48:15.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:17.001+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:48:16.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:48:17.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:17.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.525 seconds
[2025-10-04T23:48:48.084+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:48.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:48:48.096+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:48:48.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:49.983+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:48:49.908+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:48:49.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:48:50.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 2.112 seconds
[2025-10-04T23:49:20.399+0000] {processor.py:186} INFO - Started process (PID=547) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:20.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:49:20.406+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:49:20.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:21.771+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:49:21.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:49:21.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:21.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.524 seconds
[2025-10-04T23:49:52.213+0000] {processor.py:186} INFO - Started process (PID=574) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:52.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:49:52.221+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:49:52.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:53.398+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:49:53.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:49:53.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:49:53.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.283 seconds
[2025-10-04T23:50:24.204+0000] {processor.py:186} INFO - Started process (PID=601) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:24.207+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:50:24.211+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:50:24.210+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:25.299+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:50:25.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:50:25.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:25.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.295 seconds
[2025-10-04T23:50:55.755+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:55.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:50:55.764+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:50:55.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:57.070+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:50:57.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:50:57.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:50:57.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.385 seconds
[2025-10-04T23:51:27.797+0000] {processor.py:186} INFO - Started process (PID=655) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:51:27.800+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:51:27.804+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:51:27.804+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:51:29.008+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:51:28.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:51:29.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:51:29.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.361 seconds
[2025-10-04T23:51:59.504+0000] {processor.py:186} INFO - Started process (PID=682) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:51:59.508+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:51:59.513+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:51:59.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:52:00.699+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:52:00.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:52:00.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:52:00.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.272 seconds
[2025-10-04T23:52:31.073+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:52:31.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:52:31.080+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:52:31.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:52:32.169+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:52:32.152+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:52:32.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:52:32.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.241 seconds
[2025-10-04T23:53:03.012+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:03.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:53:03.020+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:53:03.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:04.065+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:53:04.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:53:04.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:04.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.120 seconds
[2025-10-04T23:53:34.271+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:34.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:53:34.281+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:53:34.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:35.688+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:53:35.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:53:35.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:53:35.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.680 seconds
[2025-10-04T23:54:06.464+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:06.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:54:06.471+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:54:06.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:07.938+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:54:07.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:54:07.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:08.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.620 seconds
[2025-10-04T23:54:38.888+0000] {processor.py:186} INFO - Started process (PID=817) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:38.891+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:54:38.894+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:54:38.893+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:39.849+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:54:39.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:54:39.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:54:40.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.229 seconds
[2025-10-04T23:55:10.402+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:10.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:55:10.408+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:55:10.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:11.520+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:55:11.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:55:11.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:11.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.209 seconds
[2025-10-04T23:55:41.811+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:41.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:55:41.820+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:55:41.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:43.188+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:55:43.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:55:43.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:55:43.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.438 seconds
[2025-10-04T23:56:14.194+0000] {processor.py:186} INFO - Started process (PID=906) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:14.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:56:14.201+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:56:14.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:15.382+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:56:15.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:56:15.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:15.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.294 seconds
[2025-10-04T23:56:46.074+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:46.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:56:46.082+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:56:46.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:47.325+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:56:47.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:56:47.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:56:47.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.324 seconds
[2025-10-04T23:57:17.853+0000] {processor.py:186} INFO - Started process (PID=960) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:17.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:57:17.859+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:57:17.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:19.199+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:57:19.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:57:19.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:19.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.435 seconds
[2025-10-04T23:57:50.223+0000] {processor.py:186} INFO - Started process (PID=987) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:50.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:57:50.230+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:57:50.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:51.169+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:57:51.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:57:51.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:57:51.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.035 seconds
[2025-10-04T23:58:22.323+0000] {processor.py:186} INFO - Started process (PID=1023) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:22.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:58:22.328+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:58:22.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:23.172+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:58:23.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:58:23.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:23.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.897 seconds
[2025-10-04T23:58:54.267+0000] {processor.py:186} INFO - Started process (PID=1050) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:54.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:58:54.274+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:58:54.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:55.617+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:58:55.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:58:55.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:58:55.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 1.418 seconds
[2025-10-04T23:59:26.493+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:26.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:59:26.499+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:59:26.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:27.384+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:59:27.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:59:27.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:27.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.961 seconds
[2025-10-04T23:59:57.693+0000] {processor.py:186} INFO - Started process (PID=1104) to work on /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:57.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telemetry_processing_dag.py for tasks to queue
[2025-10-04T23:59:57.698+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:59:57.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:58.559+0000] {logging_mixin.py:190} INFO - [2025-10-04T23:59:58.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telemetry_processing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 10, in <module>
    from tasks.load import IcebergStorage
  File "/opt/airflow/dags/tasks/load.py", line 7, in <module>
    from dags.tasks.config.settings import ICEBERG_STORAGE, BYTES_SIZE, TARGET_FILE_SIZE_MB
ImportError: cannot import name 'ICEBERG_STORAGE' from 'dags.tasks.config.settings' (/opt/airflow/dags/tasks/config/settings.py)
[2025-10-04T23:59:58.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telemetry_processing_dag.py
[2025-10-04T23:59:58.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telemetry_processing_dag.py took 0.948 seconds
