[2025-10-02T05:49:17.930+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-02T05:49:17.964+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2023-12-31T23:30:00+00:00 [queued]>
[2025-10-02T05:49:18.338+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2023-12-31T23:30:00+00:00 [queued]>
[2025-10-02T05:49:18.340+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-10-02T05:49:18.371+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): ingest_telemetry> on 2023-12-31 23:30:00+00:00
[2025-10-02T05:49:18.394+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=551) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T05:49:18.394+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'core_telemetry_pipeline', 'ingest_telemetry', 'scheduled__2023-12-31T23:30:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/telemetry_processing_dag.py', '--cfg-path', '/tmp/tmp4jshd14o']
[2025-10-02T05:49:18.398+0000] {standard_task_runner.py:72} INFO - Started process 560 to run task
[2025-10-02T05:49:18.399+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask ingest_telemetry
[2025-10-02T05:49:18.532+0000] {task_command.py:467} INFO - Running <TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2023-12-31T23:30:00+00:00 [running]> on host 159b3d08f393
[2025-10-02T05:49:18.698+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='core_telemetry_pipeline' AIRFLOW_CTX_TASK_ID='ingest_telemetry' AIRFLOW_CTX_EXECUTION_DATE='2023-12-31T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-31T23:30:00+00:00'
[2025-10-02T05:49:18.701+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-02T05:49:18.789+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 39, in ingest_telemetry
    ingestion = Ingestion()
                ^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/ingest.py", line 35, in __init__
    self.con = duckdb.connect(self.duckdb_path) if self.duckdb_path else duckdb.connect()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_duckdb.IOException: IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory
[2025-10-02T05:49:18.835+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=core_telemetry_pipeline, task_id=ingest_telemetry, run_id=scheduled__2023-12-31T23:30:00+00:00, execution_date=20231231T233000, start_date=20251002T054917, end_date=20251002T054918
[2025-10-02T05:49:18.874+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-02T05:49:18.876+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 64 for task ingest_telemetry (IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory; 560)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 39, in ingest_telemetry
    ingestion = Ingestion()
                ^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/ingest.py", line 35, in __init__
    self.con = duckdb.connect(self.duckdb_path) if self.duckdb_path else duckdb.connect()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_duckdb.IOException: IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory
[2025-10-02T05:49:18.955+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-02T05:49:18.988+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T05:49:18.992+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
