[2025-10-02T10:44:48.921+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-02T10:44:49.107+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2024-01-01T10:30:00+00:00 [queued]>
[2025-10-02T10:44:49.204+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2024-01-01T10:30:00+00:00 [queued]>
[2025-10-02T10:44:49.212+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-10-02T10:44:52.816+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): ingest_telemetry> on 2024-01-01 10:30:00+00:00
[2025-10-02T10:44:52.855+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1585) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-02T10:44:52.859+0000] {standard_task_runner.py:72} INFO - Started process 1596 to run task
[2025-10-02T10:44:52.860+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'core_telemetry_pipeline', 'ingest_telemetry', 'scheduled__2024-01-01T10:30:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/telemetry_processing_dag.py', '--cfg-path', '/tmp/tmp3731schx']
[2025-10-02T10:44:52.867+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask ingest_telemetry
[2025-10-02T10:44:53.009+0000] {task_command.py:467} INFO - Running <TaskInstance: core_telemetry_pipeline.ingest_telemetry scheduled__2024-01-01T10:30:00+00:00 [running]> on host 159b3d08f393
[2025-10-02T10:44:53.197+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='core_telemetry_pipeline' AIRFLOW_CTX_TASK_ID='ingest_telemetry' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T10:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T10:30:00+00:00'
[2025-10-02T10:44:53.205+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-02T10:44:53.291+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 39, in ingest_telemetry
    ingestion = Ingestion()
                ^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/ingest.py", line 34, in __init__
    self.con = duckdb.connect(self.duckdb_path) if self.duckdb_path else duckdb.connect()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_duckdb.IOException: IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory
[2025-10-02T10:44:53.341+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=core_telemetry_pipeline, task_id=ingest_telemetry, run_id=scheduled__2024-01-01T10:30:00+00:00, execution_date=20240101T103000, start_date=20251002T104449, end_date=20251002T104453
[2025-10-02T10:44:53.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-02T10:44:53.396+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 158 for task ingest_telemetry (IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory; 1596)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/telemetry_processing_dag.py", line 39, in ingest_telemetry
    ingestion = Ingestion()
                ^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/ingest.py", line 34, in __init__
    self.con = duckdb.connect(self.duckdb_path) if self.duckdb_path else duckdb.connect()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_duckdb.IOException: IO Error: Cannot open file "/data/metadata/pipeline.duckdb": No such file or directory
[2025-10-02T10:44:53.489+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-02T10:44:53.524+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
